config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pfcs#index'

  resources :pfcs

  resources :goals do
    collection do
      get 'search'
    end
    member do
      get 'select'
    end
  end

  resources :items do
    collection do
      get 'search'
    end
  end
  
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="top-page-header-top">
    <div class="top-pfc">
      <div class='pfc-icon'>
        <%= link_to "Your-pfc", root_path, class: "pfc-icon" %>
      </div>
    </div>
    <div class='top-page-user-button'>
      <% if user_signed_in? %>
        <div><%= link_to current_user.name, "#", class: "user-name" %></div>
        <div><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout" %></div>
      <% else %>
        <div><%= link_to 'ログイン', new_user_session_path, class: "login" %></div>
        <div><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></div>
      <% end %>
    </div>
  </div>
  <div class='nav'>
    <div><%= link_to '記録', new_pfc_path, class: "pfc-new" %></div>
    <div><%= link_to '目標', goals_path, class: "goal-set" %></div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='top-page-header'>
  <div class="top-page-header-top">
    <div class="top-pfc">
      <div class='pfc-icon'>
        <%= link_to "Your-pfc", root_path, class: "pfc-icon"%>
      </div>
    </div>
  </div>
</header>