config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pfcs#index'

  resources :pfcs

  resources :goals do
    collection do
      get 'search'
    end
    member do
      get 'select'
    end
  end

  resources :items do
    collection do
      get 'search'
    end
  end
  
end

app/models/pfc.rb
class Pfc < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :pfc_items, dependent: :destroy
  has_many :items, through: :pfc_items
  
  belongs_to :user
  belongs_to :timezone

  validates :day,                 presence: { message: "を入力してください。" }
  validates :time,                presence: { message: "を入力してください。" }
  validates :timezone_id,         presence: { message: "を選択してください。" }, numericality: { other_than: 1, message: "can't be blank" }

  def total_kcal
    pfc_items.sum(:adjusted_kcal)
  end

  def total_protein
    pfc_items.sum(:adjusted_protein)
  end

  def total_sugar
    pfc_items.sum(:adjusted_sugar)
  end

  def total_oil
    pfc_items.sum(:adjusted_oil)
  end
end

app/models/pfctype.rb
class Pfctype < ActiveHash::Base
  self.data = [
   { id: 1, name: '---' },
   { id: 2, name: 'ローファット' },
   { id: 3, name: 'ケトジェニック' },
   { id: 4, name: 'その他' },
 ]

 include ActiveHash::Associations
  has_many :goals
end

app/controllers/pfcs_controller.rb
class PfcsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: [:index, :show]
  before_action :set_pfc, only: [:edit, :update, :destroy]
  
  def index
    if current_user
      @pfcs = current_user.pfcs.includes(:items)
    else
      @pfcs = [] # ログインしていない場合は空の配列をセット
    end
    if session[:selected_goal_id].present?
      begin
        @goal = Goal.find(session[:selected_goal_id])
      rescue ActiveRecord::RecordNotFound
        session[:selected_goal_id] = nil
        flash[:alert] = "Selected goal not found. Please select a valid goal."
        redirect_to root_path
      end
    end
  end

  def new
    @pfc = Pfc.new
    @items = current_user.items
    if params[:keyword].present?
      @items = @items.where('item_name LIKE ?', "%#{params[:keyword]}%")
    end
  end

  def create
    @pfc = Pfc.new(pfc_params)
    @pfc.user = current_user
    @items = current_user.items
    selected_item_ids = params[:pfc][:item_ids] || []
    adjustment_percentages = params[:pfc][:adjustment_percentages] || {}

    if selected_item_ids.blank?
      @pfc.errors.add(:item_ids, "を選択してください。")
      render :new
      return
    end

    selected_item_ids.each do |item_id|
      percentage = adjustment_percentages[item_id.to_s] || 100
    end

    if @pfc.save
      adjust_items
      redirect_to edit_pfc_path(@pfc)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @pfc = Pfc.find(params[:id])
    @items = current_user.items
    if params[:keyword].present?
      @items = @items.where('item_name LIKE ?', "%#{params[:keyword]}%")
    end
    # 合計値を計算
    @total_kcal = @pfc.pfc_items.sum { |item| item.adjusted_kcal || item.item.item_kcal }
    @total_protein = @pfc.pfc_items.sum { |item| item.item.item_protein }
    @total_sugar = @pfc.pfc_items.sum { |item| item.item.item_sugar }
    @total_oil = @pfc.pfc_items.sum { |item| item.item.item_oil }
  end

  def update
    @pfc = Pfc.find(params[:id])
    @pfc.user = current_user
    selected_item_ids = params[:pfc][:item_ids] || []
    adjustment_percentages = params[:pfc][:adjustment_percentages] || {}

    if selected_item_ids.blank?
      @pfc.errors.add(:item_ids, "を選択してください。")
      render :edit
      return
    end

    # 既存の pfc_items を削除
    @pfc.pfc_items.destroy_all
    
    # 新しい pfc_items を作成
    selected_item_ids.each do |item_id|
      percentage = adjustment_percentages[item_id] || 100
      @pfc.pfc_items.create(item_id: item_id, adjusted_kcal: calculate_adjusted_kcal(item_id, percentage))
    end

    if @pfc.save
      redirect_to edit_pfc_path(@pfc), notice: 'Pfc was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @pfc.destroy
      redirect_to pfcs_path, notice: 'PFCが削除されました。'
    else
      redirect_to pfcs_path, alert: 'PFCの削除に失敗しました。'
    end
  end


  private

  def pfc_params
    params.require(:pfc).permit(:day, :time, :timezone_id, item_ids: []).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path, alert: "ログインが必要です"
    end
  end

  def adjust_items
    adjustment_percentages = (params[:pfc][:adjustment_percentages] || {}).transform_values(&:to_f)
    selected_item_ids = params[:pfc][:item_ids].map(&:to_i)
  
    selected_item_ids.each do |item_id|
      pfc_item = PfcItem.find_or_initialize_by(pfc: @pfc, item_id: item_id)
      item = Item.find(item_id)
      adjustment_percentage = adjustment_percentages[item_id.to_s] / 100.0
  
      pfc_item.update(
        adjusted_kcal: (item.item_kcal * adjustment_percentage).round,
        adjusted_protein: (item.item_protein * adjustment_percentage).round,
        adjusted_oil: (item.item_oil * adjustment_percentage).round,
        adjusted_sugar: (item.item_sugar * adjustment_percentage).round,
        adjustment_percentage: adjustment_percentage
      )
    end
  end

  def set_pfc
    @pfc = Pfc.find(params[:id])
  end

  def calculate_adjusted_kcal(item_id, percentage)
    item = Item.find(item_id)
    item.item_kcal * (percentage.to_f / 100.0)
  end

end

app/helpers/pfc_helper.rb
module PfcHelper
end

app/views/pfcs/edit.html.erb
<%= render "shared/header" %>
<div class="pfc-new-pfc">
  <div class="pfc-base">
    <div class='pfc-sell-title'>
      食材を登録する
    </div>

    <div class='pfc-graph' id="pfc-graph">
    </div>

    <div class="pfc-item-select-index">
      選択中食材一覧
      <ul>
        <% @pfc.pfc_items.each do |pfc_item| %> <!-- pfc_items を使用して中間モデルのデータを取得 -->
          <li>
            <span id="kcal_<%= pfc_item.item.id %>" data-original-kcal="<%= pfc_item.item.item_kcal %>">
              <%= pfc_item.item.item_name %> - <%= pfc_item.adjusted_kcal || pfc_item.item.item_kcal %> kcal - タンパク質<%= pfc_item.item.item_protein %>g - 糖質<%= pfc_item.item.item_sugar %>g - 脂質<%= pfc_item.item.item_oil %>g
            </span>
          </li>
        <% end %>
      </ul>
    </div> 

    <div >
      合計カロリー: <%= @total_kcal %> kcal -
      合計タンパク質: <%= @total_protein %> g -
      合計糖質: <%= @total_sugar %> g -
      合計脂質: <%= @total_oil %> g
    </div>

    <div class="pfc-item-new-button">
      <%= link_to new_item_path , class: "pfc-item-new-link" do %>
        <span>新しい食材を登録する</span>
      <% end %>
    </div>

    <div>
      <!-- 検索フォーム -->
      <%= form_with(url: search_items_path, method: :get, local: true, id: 'item-search-form', class: 'pfc-item-search') do |search_form| %>
        <%= search_form.text_field :keyword, placeholder: "食材を検索", id: 'item-search-keyword', class: 'pfc-item-search-keyword' %>
      <% end %>
    </div>

    <div class="pfc-item-regisration">
      <!-- フォームに追加するアイテムのチェックボックス -->
      <%= form_with(model: @pfc, local: true) do |form| %>

        <!-- その他のフォームフィールド -->
        <div class="pfc-item-time">
          <%= form.date_field :day, class: "pfc-time-select-day", value: Date.today %>
          <%= form.collection_select(:timezone_id, Timezone.all, :id, :name, {}, { class: "pfc-timezone-select", id: "timezone_id" }) %>
          <%= form.time_field :time, class: "pfc-time-select-time", value: Time.now.strftime("%H:%M") %>
        </div>

        <div class="pfc-item-regisration-index-title">
          ＜アイテム一覧＞
        </div>

        <div id="search-results-container">
          <%= render 'items/search_results', items: @items %>
        </div>

        <div class="pfc-item-form-submit">
          <%= form.submit "保存する", class:"pfc-item-sell-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to(root_path, class: 'record-btn') do %>
    <span class='record-btn-text'>PFC一覧</span>
<% end %>

app/views/pfcs/index.html.erb
<%= render "shared/header" %>

<h2>Selected Goal</h2>
<% if @goal %>
  <div>
    <p><strong>Kcal:</strong> <%= @goal.goal_kcal %> kcal</p>
    <p><strong>Sugar:</strong> <%= @goal.goal_sugar %> g</p>
    <p><strong>Oil:</strong> <%= @goal.goal_oil %> g</p>
    <p><strong>Protein:</strong> <%= @goal.goal_protein %> g</p>
    <p><strong>Category:</strong> <%= @goal.pfctype.name %></p>
  </div>
<% else %>
  <p>No goal found.</p>
<% end %>

<div>
  <%= link_to items_path do %>
        <span >食材一覧</span>
  <% end %>
</div>

<h1>PFC一覧</h1>

<% if @pfcs.any? %>
  <table>
    <thead>
      <tr>
        <th>カロリー (kcal)</th>
        <th>タンパク質 (g)</th>
        <th>糖質 (g)</th>
        <th>脂質 (g)</th>
        <th>食材</th>
        <th>編集</th>
      </tr>
    </thead>
    <tbody>
      <% @pfcs.each do |pfc| %>
        <tr>
          <td><%= pfc.total_kcal %></td> <!-- 例: カロリー合計 -->
          <td><%= pfc.total_protein %></td> <!-- 例: タンパク質合計 -->
          <td><%= pfc.total_sugar %></td> <!-- 例: 糖質合計 -->
          <td><%= pfc.total_oil %></td> <!-- 例: 脂質合計 -->
          <td>
            <ul>
              <% pfc.items.each do |item| %>
                <li><%= item.item_name %></li> <!-- 各食材の名前を表示 -->
              <% end %>
            </ul>
          </td>
          <td>
            <%= link_to '編集', edit_pfc_path(pfc) %> <!-- 編集リンク -->
            <%= link_to "削除", pfc_path(pfc), data: {turbo_method: :delete} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>登録されたPFCはありません。</p>
<% end %>

app/views/pfcs/new.html.erb
<%= render "shared/header" %>
<div class="pfc-new-pfc">
  <div class="pfc-base">
    <div class='pfc-sell-title'>
      食材を登録する
    </div>

    <div class='pfc-graph' id="pfc-graph">
    </div>

    <%# <div class="pfc-item-select-index">
      選択中食材一覧
    </div> %>

    <div class="pfc-item-new-button">
      <%= link_to new_item_path , class: "pfc-item-new-link" do %>
        <span>新しい食材を登録する</span>
      <% end %>
    </div>

    <div>
      <!-- 検索フォーム -->
      <%= form_with(url: search_items_path, method: :get, local: true, id: 'item-search-form', class: 'pfc-item-search') do |search_form| %>
        <%= search_form.text_field :keyword, placeholder: "食材を検索", id: 'item-search-keyword', class: 'pfc-item-search-keyword' %>
      <% end %>
    </div>

    <div class="pfc-item-regisration">
      <!-- フォームに追加するアイテムのチェックボックス -->
      <%= form_with(model: @pfc, local: true) do |form| %>

        <!-- その他のフォームフィールド -->
        <div class="pfc-item-time">
          <%= form.date_field :day, class: "pfc-time-select-day", value: Date.today %>
          <%= form.collection_select(:timezone_id, Timezone.all, :id, :name, {}, { class: "pfc-timezone-select", id: "timezone_id" }) %>
          <%= form.time_field :time, class: "pfc-time-select-time", value: Time.now.strftime("%H:%M") %>
        </div>

        <div class="pfc-item-regisration-index-title">
          ＜アイテム一覧＞
        </div>

        <div id="search-results-container">
          <%= render 'items/search_results', items: @items %>
        </div>

        <div class="pfc-item-form-submit">
          <%= form.submit "保存する", class:"pfc-item-sell-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to(root_path, class: 'record-btn') do %>
    <span class='record-btn-text'>PFC一覧</span>
<% end %>

app/views/pfcs/show.html.erb
<%= render "shared/header" %>