config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pfcs#index'

  resources :pfcs

  resources :goals do
    collection do
      get 'search'
    end
    member do
      get 'select'
    end
  end

  resources :items do
    collection do
      get 'search'
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :pfc_items
  has_many :pfcs, through: :pfc_items

  belongs_to :user
  
  validates :item_name, presence: true
  validates :item_kcal, presence: true
  validates :item_oil, presence: true
  validates :item_protein, presence: true
  validates :item_sugar, presence: true
end

app/models/pfc.rb
class Pfc < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :pfc_items, dependent: :destroy
  has_many :items, through: :pfc_items
  
  belongs_to :user
  belongs_to :timezone

  validates :day,                 presence: { message: "を入力してください。" }
  validates :time,                presence: { message: "を入力してください。" }
  validates :timezone_id,         presence: { message: "を選択してください。" }, numericality: { other_than: 1, message: "can't be blank" }

  def total_kcal
    pfc_items.sum(:adjusted_kcal)
  end

  def total_protein
    pfc_items.sum(:adjusted_protein)
  end

  def total_sugar
    pfc_items.sum(:adjusted_sugar)
  end

  def total_oil
    pfc_items.sum(:adjusted_oil)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index 
    if current_user.present?
      @items = current_user.items.order("created_at DESC")
      @items = @items.where('name LIKE ?', "%#{params[:keyword]}%") if params[:keyword].present?
      @items = @items.where(store_id: params[:store_id]) if params[:store_id].present?
    else
      @items = []
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else 
      render :new
    end
  end

  def show
  end

  def destroy
    item = Item.find(params[:id])
    goal.destroy
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    goal.update(item_params)
    redirect_to items_path
  end

  def search
    @items = current_user.items
    @pfc = Pfc.new
    if params[:keyword].present?
      @items = @items.where('item_name LIKE ?', "%#{params[:keyword]}%")
    end
  
    if request.xhr?
      render partial: 'search_results', locals: { items: @items }
    else
      @items = Item.all
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_kcal, :item_oil, :item_protein, :item_sugar, :item_name, :store_id, :remarks).merge(user_id: current_user.id)
  end

  def filtered_items(scope)
    items = scope.order("created_at DESC")
    items = items.where('item_name LIKE ?', "%#{params[:keyword]}%") if params[:keyword].present?
    items = items.where(store_id: params[:store_id]) if params[:store_id].present?
    items
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_search_results.html.erb
<div id="search-results">
  <% @items.each do |item| %>
    <div class="item-checkbox-percentage">
      <div class="item-pfc-checkbox">
        <%= check_box_tag 'pfc[item_ids][]', item.id, @pfc.item_ids.include?(item.id), class: 'item-checkbox', data: { item_id: item.id } %>
      </div>
      <div class="item-pfc-percentage-graph">
        <canvas id="macrosChart_<%= item.id %>"></canvas>
      </div>
      <div class="item-pfc-percentage-index">
        <div class="item-pfc-percentage-item-name">
          <%= label_tag "pfc_item_#{item.id}", item.item_name %>
        </div>
        <div class="item-pfc-percentage-index-item">
          <div class="item-pfc-percentage-index-item-contents">カロリー  <span class="item-pfc-percentage-index-item-value" id="item-kcal_<%= item.id %>"><%= item.item_kcal %></span> kcal</div>
          <div class="item-pfc-percentage-index-item-contents">タンパク質  <span class="item-pfc-percentage-index-item-value" id="item-protein_<%= item.id %>"><%= item.item_protein %></span> g</div>
          <div class="item-pfc-percentage-index-item-contents">糖質  <span class="item-pfc-percentage-index-item-value" id="item-sugar_<%= item.id %>"><%= item.item_sugar %></span> g</div>
          <div class="item-pfc-percentage-index-item-contents">脂質  <span class="item-pfc-percentage-index-item-value" id="item-oil_<%= item.id %>"><%= item.item_oil %></span> g</div>
        </div>
      </div>
      <div class="item-pfc-percentage-ratio">
        <%= number_field_tag "pfc[adjustment_percentages][#{item.id}]", 100, step: 0.1, min: 0, id: "percentage_#{item.id}", class: "item-pfc-new-percentage-input",style: 'display: none;' %>
        <%= label_tag "percentage_#{item.id}", " (%)" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div>
  <% if @items.present? %>
    <% @items.each do |item| %>
      <%= content_tag :span, item.item_name %>
      <%= content_tag :span, item.item_kcal %>
      <%= content_tag :span, item.item_protein %>
      <%= content_tag :span, item.item_oil %>
      <%= content_tag :span, item.item_sugar %>
      <%= content_tag :span, Store.find(item.store_id).name %> 
      <%= content_tag :span, item.remarks %>
    <% end %>
  <% else %>
    <p>No items found.</p>
  <% end %>
</div>

app/views/items/new.html.erb
<%= render "shared/header" %>
<body class="items-new">
  <div class= "item-new">
    <div class='item-contents'>
      <div class='goal-sell-title'>
        食材を登録する
      </div>
<%# グラフ %>
      <div class='item-graph'>
        <canvas id="macrosChart"></canvas>
      </div>
      <div class='item-form'>
        <%= form_with(model: @item, local: true) do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
<%# メニュー名 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              メニュー名
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.text_field :item_name, placeholder: "メニュー名", id: "item_name", class: "item-form-field-text" %>
                <div class='item-form-kcal'>
                </div>
              </div>
            </div>
          </div>
<%# タンパク質 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              タンパク質
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.number_field :item_protein, placeholder: "タンパク質", id: "item_protein", class: "item-form-field-text"%>
                <div class='item-form-g'>
                  g
                </div>
              </div>
            </div>
          </div>
<%# 糖質 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              糖質
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.number_field :item_sugar, placeholder: "糖質", id: "item_sugar", class: "item-form-field-text" %>
                <div class='item-form-g'>
                  g
                </div>
              </div>
            </div>
          </div>
<%# 脂質 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              脂質
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.number_field :item_oil, placeholder: "脂質", id: "item_oil", class: "item-form-field-text" %>
                <div class='item-form-g'>
                  g
                </div>
              </div>
            </div>
          </div>
<%# 合計カロリー %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              合計カロリー
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.number_field :item_kcal, placeholder: "kcal", id: "item_kcal", class: "item-form-field-text"%>
                <div class='item-form-kcal'>
                  kcal
                </div>
              </div>
            </div>
          </div>
<%# 入手場所 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
              入手場所
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.collection_select(:store_id, Store.all, :id, :name, {}, { class: "item-form-field-text", id: "store_id" }) %>
                <div class='item-form-g'>
                </div>
              </div>
            </div>
          </div>
<%# 備考欄 %>
          <div class='item-form-input'>
            <div class='item-form-pfc'>
            </div>
            <div class="item-form-pfc-right">
              <div class='item-form-field'>
                <%= f.text_area :remarks, placeholder: "備考欄", id: "remarks", class: "item-form-field-area"%>
                <div class='item-form-g'>
                </div>
              </div>
            </div>
          </div>
<%# 決定ボタン %>
          <div class='item-form-input item-form-submit'>
            <%= f.submit "決定する", class: "item-new-sell-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>