config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pfcs#index'

  resources :pfcs

  resources :goals do
    collection do
      get 'search'
    end
    member do
      get 'select'
    end
  end

  resources :items do
    collection do
      get 'search'
    end
  end
  
end

app/models/goal.rb
class Goal < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :pfctype
  belongs_to :user
  

  validates :goal_kcal, presence: true
  validates :goal_oil, presence: true
  validates :goal_protein, presence: true
  validates :goal_sugar, presence: true
  
  def protein_percentage
    (goal_protein.to_f * 4 / total_calories * 100).floor
  end

  def sugar_percentage
    (goal_sugar.to_f * 4 / total_calories * 100).floor
  end

  def oil_percentage
    (goal_oil.to_f * 9 / total_calories * 100).floor
  end

  def total_calories
    (goal_protein * 4) + (goal_sugar * 4) + (goal_oil * 9)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @goals = current_user.goals.order("created_at DESC")
    @goals = @goals.where('name LIKE ?', "%#{params[:keyword]}%") if params[:keyword].present?
    @goals = @goals.where(pfctype_id: params[:pfctype_id]) if params[:pfctype_id].present?
    Rails.logger.debug "Goals: #{@goals.inspect}"
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to goals_path
    else 
      render :new
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to goals_path
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    goal = Goal.find(params[:id])
    goal.update(goal_params)
    redirect_to goals_path
  end

  def search
    @goals = current_user.goals.order("created_at DESC")
    @goals = @goals.where('name LIKE ?', "%#{params[:keyword]}%") if params[:keyword].present?
    @goals = @goals.where(pfctype_id: params[:pfctype_id]) if params[:pfctype_id].present?
    render :index
  end

  def select
    session[:selected_goal_id] = params[:id]
    redirect_to pfcs_path
  end

  private

  def goal_params
    params.require(:goal).permit(:goal_kcal, :goal_oil, :goal_protein, :goal_sugar, :pfctype_id).merge(user_id: current_user.id)
  end

  def correct_user
    @goal = Goal.find(params[:id])
    redirect_to(root_url) unless current_user == @goal.user
  end


end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
<%= render "shared/header" %>

<div class='goal-new'>
  <div class='goal-contents'>
    <h3 class='goal-sell-title'>目標を設定する</h3>
    <div class='goal-graph'>グラフ</div>
    <div class='goal-form'>
      <%= form_with(model: @goal, local: true) do |f| %>
        
        <%= render 'shared/error_messages', model: f.object %>

        <div class='goal-form-input'>
          <div class='goal-form-pfc'>kcal</div>
          <div class='goal-form-field'>
            <%= f.number_field :goal_kcal, placeholder: "kcal" %>
            <div class='goal-form-kcal'>kcal</div>
          </div>
        </div>
        <div class='goal-form-input'>
          <div class='goal-form-pfc'>タンパク質</div>
          <div class='goal-form-field'>
            <%= f.number_field :goal_protein, placeholder: "タンパク質" %>
            <div class='goal-form-g'>g</div>
          </div>
        </div>
        <div class='goal-form-input'>
          <div class='goal-form-pfc'>糖質</div>
          <div class='goal-form-field'>
            <%= f.number_field :goal_sugar, placeholder: "糖質" %>
            <div class='goal-form-g'>g</div>
          </div>
        </div>
        <div class='goal-form-input'>
          <div class='goal-form-pfc'>脂質</div>
          <div class='goal-form-field'>
            <%= f.number_field :goal_oil, placeholder: "脂質" %>
            <div class='goal-form-g'>g</div>
          </div>
        </div>
        <div class='goal-form-input'>
          <div class='goal-form-pfc'>カテゴリー</div>
          <%= f.collection_select(:pfctype_id, Pfctype.all, :id, :name, {}, {class:"goal-pfctype-select"}) %>
        </div>
        <div class='goal-form-input goal-form-submit'>
          <%= f.submit "決定する", class: "goal-new-sell-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/index.html.erb
<%= render "shared/header" %>

<body class="goals-index">
  <div class='goal-top-record'>
    <%= link_to new_goal_path, class: 'custom-btn' do %>
      <span class='custom-btn-text'>登録する</span>
    <% end %>
  </div>

  <div class='goal-search'>
    <%= form_with(url: search_goals_path, local: true, method: :get, class: "goal-search-form") do |form| %>
      <%= form.collection_select :pfctype_id, Pfctype.all, :id, :name, { include_blank: 'すべて' }, class: "goal-search-input" %>
      <%= form.submit "検索", class: "goal-search-btn" %>
    <% end %>
  </div>

  <div class='goal-mein'>
    <% @goals.each do |goal| %>
      <div class='goal-item' data-goal-id="<%= goal.id %>">
        <div class='goal-item-select'>
          <div class='goal-item-select-favorite'>
            <%= link_to '★', select_goal_path(goal), class: 'goal-item-select-font'%>
          </div>
          <div class='goal-item-select-edit'>
            <%= link_to '編集', edit_goal_path(goal.id), class: 'goal-item-select-edit-btn' %>
          </div>
          <div class='goal-item-select-delete'>
            <%= link_to '削除', "/goals/#{goal.id}", data: { turbo_method: :delete }, class: 'goal-item-select-delete-btn' %>
          </div>
        </div>
        <div class='goal-item-left'>
          <div class='goal-item-kcal'><%= content_tag :span, goal.goal_kcal, class: 'goal-kcal-value' %> kcal </div>
          <div class='goal-item-graph'>
            <canvas id="macrosChart-<%= goal.id %>"></canvas>
            <div id="goal-data-<%= goal.id %>" style="display:none;">
              {
                "goal_protein": <%= goal.goal_protein %>,
                "goal_sugar": <%= goal.goal_sugar %>,
                "goal_oil": <%= goal.goal_oil %>
              }
            </div>
          </div>
        </div>
        <div class='goal-item-right'>
          <div class='goal-item-categories'><%= goal.pfctype.name %> </div>
          <div class='goal-item-pfcs'> 
            <div class='goal-item-pfc'>
              <div class='goal-item-pfc-left'>
                <div class='goal-item-pfc-percent'><%= goal.protein_percentage %></div>
                <div class='goal-item-pfc-item'>％</div> 
              </div>
              <div class='goal-item-pfc-right'>
                <div class='goal-item-pfc-item-value'>タンパク質:</div>
                <%= content_tag :span, goal.goal_protein, class: 'goal-item-pfc-value' %> 
                <div class='goal-item-pfc-item'>g</div> 
              </div>
            </div>
            <div class='goal-item-pfc'>
              <div class='goal-item-pfc-left'>
                <div class='goal-item-pfc-percent'><%= goal.sugar_percentage %></div>
                <div class='goal-item-pfc-item'>％</div> 
              </div>
              <div class='goal-item-pfc-right'>
                <div class='goal-item-pfc-item-value'>糖質:</div>
                <%= content_tag :span, goal.goal_sugar, class: 'goal-item-pfc-value' %> 
                <div class='goal-item-pfc-item'>g</div> 
              </div>
            </div>
            <div class='goal-item-pfc'>
              <div class='goal-item-pfc-left'>
                <div class='goal-item-pfc-percent'><%= goal.oil_percentage %></div>
                <div class='goal-item-pfc-item'>％</div> 
              </div>
              <div class='goal-item-pfc-right'>
                <div class='goal-item-pfc-item-value'>脂質:</div>
                <%= content_tag :span, goal.goal_oil, class: 'goal-item-pfc-value' %> 
                <div class='goal-item-pfc-item'>g</div> 
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="goal-index-bottom">
</div>
</body>

<%= link_to(new_goal_path, class: 'record-btn') do %>
    <span class='record-btn-text'>登録する</span>
<% end %>

app/views/goals/new.html.erb
<%= render "shared/header" %>
<body class="goals-new">
  <div class='goal-new'>
    <div class='goal-contents'>
      <div class='goal-sell-title'>目標を設定する</div>
      <div class='goal-graph'>
        <canvas id="macrosChart"></canvas>
      </div>
      <div class='goal-form'>
        <%= form_with(model: @goal, local: true) do |f| %>
          
          <div class='goal-form-input'>
            <div class='goal-form-pfc'>合計カロリー</div>
            <div class='goal-form-field'>
              <%= f.number_field :goal_kcal, placeholder: "kcal", id: "goal_kcal" %>
              <div class='goal-form-kcal'>kcal</div>
            </div>
          </div>
          <div class='goal-form-input'>
            <div class='goal-form-pfc'>カテゴリー</div>
            <%= f.collection_select(:pfctype_id, Pfctype.all, :id, :name, {}, { class: "goal-pfctype-select", id: "pfctype_id" }) %>
          </div>
          <div class='goal-form-input'>
            <div class='goal-form-pfc'>タンパク質</div>
            <div class='goal-form-field'>
              <%= f.number_field :goal_protein, placeholder: "タンパク質", id: "goal_protein" %>
              <div class='goal-form-g'>g</div>
            </div>
          </div>
          <div class='goal-form-input'>
            <div class='goal-form-pfc'>糖質</div>
            <div class='goal-form-field'>
              <%= f.number_field :goal_sugar, placeholder: "糖質", id: "goal_sugar" %>
              <div class='goal-form-g'>g</div>
            </div>
          </div>
          <div class='goal-form-input'>
            <div class='goal-form-pfc'>脂質</div>
            <div class='goal-form-field'>
              <%= f.number_field :goal_oil, placeholder: "脂質", id: "goal_oil" %>
              <div class='goal-form-g'>g</div>
            </div>
          </div>
          <div class='goal-form-input goal-form-submit'>
            <%= f.submit "決定する", class: "goal-new-sell-btn" %>
          </div>
        <% end %>
      </div>
    </div>
 </div>
</div>